### ISSUE TITLE
APPID要怎么才能获得？

### ISSUE THREAD

**Issue by TonyRenHK** [TencentCloudBase/image-node-sdk#2]
请问这里appid需要怎么获得？

**Comment by lcxfs1991** [comment]
@TonyRenHK 请参考该教程：

https://github.com/TencentCloudBase/mp-book/blob/master/guide/readme.md#3-%E5%9C%A8%E8%87%AA%E5%B7%B1%E7%9A%84%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%88%96%E8%80%85%E7%94%B5%E8%84%91%E6%9C%AC%E5%9C%B0%E7%9A%84node%E8%BF%90%E8%A1%8C%E7%8E%AF%E5%A2%83%E9%87%8C%E4%B8%8D%E6%98%AF%E4%BA%91%E5%BC%80%E5%8F%91%E8%B0%83%E7%94%A8%E4%BA%91%E5%BC%80%E5%8F%91%E7%9A%84%E6%9C%8D%E5%8A%A1%E8%A6%81%E5%81%9A%E5%93%AA%E4%BA%9B%E9%A2%9D%E5%A4%96%E9%85%8D%E7%BD%AE
