### ISSUE TITLE
贵公司的SDK和平台实在是太乱了

### ISSUE THREAD

**Issue by jayasme** [TencentCloudBase/image-node-sdk#4]
我之前安装了一个`tencentcloud-sdk-nodejs`，用来做人脸识别的，然后你们这个又搞一个`image-node-sdk`，为什么同样的功能要分这么多SDK，还有贵公司的开发平台也是各种乱，有dev.tencent.com，open.tencent.com，open.qq.com，open.weixin.qq.com，有的要QQ号登录，有的要微信号登录，根本是一团乱。

**Comment by lcxfs1991** [comment]
@jayasme 你好。image-node-sdk 底层使用的是云 API2.0。之所以会写这个，是因为之前大半年API还没有更新上来，因此我为了方便写Node的童鞋，义务写了这个。目前AI已经部份接入了云 API 3.0，这些已接入的可以使用 `tencentcloud-sdk-nodejs`，未接入的还是得用 `image-node-sdk`。但大趋势下，会逐步迁移往 `tencentcloud-sdk-nodejs`。

对你造成的不便，希望见谅。
